DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS tasks_comments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS users_roles;

create table comments
(
    id         bigint generated by default as identity,
    created_at timestamp(6),
    text       varchar(255),
    updated_at timestamp(6),
    author_id  bigint,
    primary key (id)
);
create table roles
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
create table tasks
(
    id          bigint generated by default as identity,
    created_at  timestamp(6),
    description varchar(255),
    priority    varchar(255) not null check (priority in ('HIGH', 'MEDIUM', 'LOW')),
    status      varchar(255) not null check (status in ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
    task_name   varchar(255) not null,
    updated_at  timestamp(6),
    assignee_id bigint,
    author_id   bigint       not null,
    primary key (id)
);
create table tasks_comments
(
    task_id     bigint not null,
    comments_id bigint not null
);

create table users
(
    id       bigint generated by default as identity,
    email    varchar(255) not null,
    password varchar(255)  not null,
    username varchar(255) not null,
    primary key (id)
);
create table users_roles
(
    user_id bigint  not null,
    role_id integer not null
);

MERGE INTO roles AS target
USING (VALUES (1, 'ROLE_USER'), (2, 'ROLE_ADMIN')) AS source(id, name)
    ON target.id = source.id
    WHEN NOT MATCHED THEN
INSERT (id, name) VALUES (source.id, source.name);

-- Insert users data
INSERT INTO users (id, username, password, email)
VALUES (1, 'user', '$2a$12$I8sfXSRHtfYtJ4x7AmeKO.grcQFdz6UONbFuknDXK0i5UEslKOFMy', 'user@gmail.com'),
       (2, 'admin', '$2a$12$s0.nukt.h1a3KLrdsnmTkesaO07v/JkQnAzDoGp9AhCugLDcKqVZO', 'admin@gmail.com');

-- Insert users_roles data (do nothing if already exists)
MERGE INTO users_roles USING (
    VALUES (1, 1), (2, 2)
) AS source (user_id, role_id)
    ON users_roles.user_id = source.user_id AND users_roles.role_id = source.role_id
    WHEN NOT MATCHED THEN INSERT (user_id, role_id) VALUES (source.user_id, source.role_id);

