version: '3.8'
services:
  # Spring Boot Application
  tms:
    container_name: tms_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/resources
    env_file:
      - app_variables.env

  # PostgresSQL Database
  postgres_tms:
    container_name: postgres_tms
    image: postgres:latest
    env_file:
        - db_variables.env
    ports:
      - "5432:5432"

